// SUP F4SE — CommonLibF4 entry point (Phase 0, see MODERNIZATION_PLAN.md).
//
// Replaces the legacy F4SEPlugin_Query / F4SEPlugin_Load in src/SUP_F4SE.cpp.
// The plugin version data is generated by the commonlibf4.plugin rule
// (see commonlibf4-plugin.cpp.in) and exported as F4SEPlugin_Version.

#include "PCH.h"

#include "sup/util/CrashDump.h"

// Legacy module init — defined in src/SUP_F4SE.cpp (Phase 3).
bool SUP_F4SE_PluginLoad();
void MessageCallback(F4SE::MessagingInterface::Message* a_msg);

namespace
{
	void MessageHandler(F4SE::MessagingInterface::Message* a_msg)
	{
		MessageCallback(a_msg);
	}
}

F4SE_PLUGIN_LOAD(const F4SE::LoadInterface* a_f4se)
{
	// Capture a minidump on any fatal exception before doing anything else — the
	// crash evidence survives even when Windows WER produces no artifacts.
	sup::crash::Install();

	F4SE::Init(a_f4se, {
		.logName        = "SUP_F4SE",  // CommonLibF4 appends ".log" itself
		.logPattern     = "[%Y-%m-%d %H:%M:%S.%e] [%l] %v",
		.logRotate      = 10,
		.trampoline     = true,  // Phase 4: hooks install via REL::GetTrampoline()
		.trampolineSize = 2048,  // 18 hook branches + headroom
	});

	if (const auto* messaging = F4SE::GetMessagingInterface()) {
		messaging->RegisterListener(MessageHandler);
	} else {
		REX::CRITICAL("Failed to get messaging interface");
		return false;
	}

	// Phase 3: the legacy load path — cosave serialization, Papyrus registration,
	// INI processing, PEX SHA1 check, event/pastebin tables, Building Bridges init.
	if (!SUP_F4SE_PluginLoad()) {
		REX::CRITICAL("SUP F4SE legacy load path failed");
		return false;
	}

	REX::INFO("SUP F4SE loaded (v0.7.7)");
	return true;
}
